#!/usr/bin/env python3
"""
Скрипт для авторизации в YouTube и экспорта cookies
Использует Playwright для автоматизации браузера
"""

import json
import sys
from playwright.sync_api import sync_playwright
import time

def export_cookies_to_netscape(cookies, output_file):
    """Конвертирует cookies в формат Netscape для yt-dlp"""
    with open(output_file, 'w') as f:
        f.write("# Netscape HTTP Cookie File\n")
        f.write("# This file is generated by Playwright. Do not edit.\n\n")
        
        for cookie in cookies:
            domain = cookie.get('domain', '')
            flag = 'TRUE' if domain.startswith('.') else 'FALSE'
            path = cookie.get('path', '/')
            secure = 'TRUE' if cookie.get('secure', False) else 'FALSE'
            expiration = str(int(cookie.get('expires', -1)))
            name = cookie.get('name', '')
            value = cookie.get('value', '')
            
            f.write(f"{domain}\t{flag}\t{path}\t{secure}\t{expiration}\t{name}\t{value}\n")

def main():
    print("🚀 Запуск браузера для авторизации в YouTube...")
    print("=" * 60)
    
    with sync_playwright() as p:
        # Запускаем браузер в headless=False чтобы видеть окно
        browser = p.chromium.launch(
            headless=False,
            args=[
                '--no-sandbox',
                '--disable-setuid-sandbox',
                '--disable-dev-shm-usage',
                '--disable-blink-features=AutomationControlled'
            ]
        )
        
        context = browser.new_context(
            viewport={'width': 1280, 'height': 720},
            user_agent='Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'
        )
        
        page = context.new_page()
        
        print("📱 Открываем YouTube...")
        page.goto('https://www.youtube.com', wait_until='networkidle')
        
        print("\n" + "=" * 60)
        print("⚠️  ВАЖНО: Авторизуйтесь в YouTube через браузер!")
        print("=" * 60)
        print("\n1. В открывшемся окне браузера нажмите 'Войти'")
        print("2. Введите email и пароль Google")
        print("3. Пройдите двухфакторную аутентификацию если требуется")
        print("4. Дождитесь полной загрузки главной страницы YouTube")
        print("5. После успешной авторизации вернитесь в терминал")
        print("\n" + "=" * 60)
        
        input("\n✅ Нажмите Enter после того как авторизовались в YouTube...")
        
        print("\n🔄 Проверяем авторизацию...")
        time.sleep(2)
        
        # Получаем cookies
        cookies = context.cookies()
        
        if not cookies:
            print("❌ Ошибка: Cookies не найдены!")
            browser.close()
            sys.exit(1)
        
        print(f"✅ Получено {len(cookies)} cookies")
        
        # Сохраняем в формате Netscape для yt-dlp
        output_file = '/opt/telegram-cover-bot/youtube_cookies.txt'
        export_cookies_to_netscape(cookies, output_file)
        
        print(f"\n✅ Cookies успешно сохранены в: {output_file}")
        print("\n📊 Статистика:")
        print(f"   - Всего cookies: {len(cookies)}")
        print(f"   - Домен: youtube.com")
        
        # Также сохраняем в JSON для отладки
        json_file = '/opt/telegram-cover-bot/youtube_cookies.json'
        with open(json_file, 'w') as f:
            json.dump(cookies, f, indent=2)
        print(f"   - JSON backup: {json_file}")
        
        print("\n🎉 Готово! Теперь перезапустите бота:")
        print("   systemctl restart telegram-cover-bot")
        
        browser.close()

if __name__ == '__main__':
    try:
        main()
    except KeyboardInterrupt:
        print("\n\n❌ Прервано пользователем")
        sys.exit(1)
    except Exception as e:
        print(f"\n❌ Ошибка: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)
