from aiogram import Router, F
from aiogram.types import Message, CallbackQuery, Document, InlineKeyboardMarkup, InlineKeyboardButton
from aiogram.filters import Command
from aiogram.fsm.context import FSMContext
from aiogram.fsm.state import State, StatesGroup
from config import START_MESSAGE, HELP_MESSAGE, ABOUT_MESSAGE, ADMIN_ID
from utils.keyboards import get_start_keyboard, get_source_selection_keyboard
import logging
import os
import re

router = Router()
logger = logging.getLogger(__name__)

COOKIES_PATH = "/opt/telegram-cover-bot/youtube_cookies.txt"


class CookiesStates(StatesGroup):
    waiting_for_cookies = State()


def parse_cookies_text(text: str) -> str:
    """Parse cookies from text (ytdlnis/Netscape format) and return valid Netscape cookie file content."""
    lines = text.strip().split('\n')
    cookie_lines = []

    for line in lines:
        line = line.strip()
        if not line or line.startswith('#'):
            continue

        # Split by tab or multiple spaces
        parts = re.split(r'\t+', line)
        if len(parts) < 7:
            # Try splitting by spaces (ytdlnis format)
            parts = re.split(r'\s+', line, maxsplit=6)

        if len(parts) < 7:
            continue

        domain = parts[0]
        # Validate it looks like a cookie line
        if not ('youtube.com' in domain or 'google' in domain or 'doubleclick' in domain):
            continue

        # Reconstruct as tab-separated
        cookie_lines.append('\t'.join(parts[:7]))

    if not cookie_lines:
        return ""

    header = "# Netscape HTTP Cookie File\n# This file is generated by yt-dlp. Do not edit.\n\n"
    return header + '\n'.join(cookie_lines) + '\n'


@router.message(Command("start"))
async def cmd_start(message: Message):
    """Обработчик команды /start"""
    await message.answer(
        START_MESSAGE,
        reply_markup=get_start_keyboard(),
        parse_mode="Markdown"
    )

@router.message(Command("help"))
async def cmd_help(message: Message):
    """Обработчик команды /help"""
    await message.answer(
        HELP_MESSAGE,
        parse_mode="Markdown"
    )

@router.message(Command("about"))
async def cmd_about(message: Message):
    """Обработчик команды /about"""
    await message.answer(
        ABOUT_MESSAGE,
        parse_mode="Markdown"
    )

@router.callback_query(F.data == "start_search")
async def callback_start_search(callback: CallbackQuery):
    """Обработчик кнопки 'Начать поиск'"""
    await callback.message.edit_text(
        "🎵 **Отправьте название трека или исполнителя**\n\n"
        "Примеры:\n"
        "• Imagine Dragons Believer\n"
        "• Coldplay\n"
        "• The Beatles Yesterday\n"
        "• Eminem Lose Yourself\n\n"
        "После отправки запроса выберите источник для поиска.",
        parse_mode="Markdown"
    )
    await callback.answer()

@router.callback_query(F.data == "new_search")
async def callback_new_search(callback: CallbackQuery):
    """Обработчик кнопки 'Новый поиск'"""
    await callback.message.edit_text(
        "🎵 **Отправьте название трека или исполнителя**\n\n"
        "Примеры:\n"
        "• Imagine Dragons Believer\n"
        "• Coldplay\n"
        "• The Beatles Yesterday\n"
        "• Eminem Lose Yourself\n\n"
        "После отправки запроса выберите источник для поиска.",
        parse_mode="Markdown"
    )
    await callback.answer()

@router.callback_query(F.data == "help")
async def callback_help(callback: CallbackQuery):
    """Обработчик кнопки 'Помощь'"""
    await callback.message.answer(
        HELP_MESSAGE,
        parse_mode="Markdown"
    )
    await callback.answer()

@router.callback_query(F.data == "noop")
async def callback_noop(callback: CallbackQuery):
    """Обработчик для кнопок без действия (например, индикатор страницы)"""
    await callback.answer()

@router.message(Command("upload_cookies", "auth_youtube", "cookies"))
async def cmd_upload_cookies(message: Message, state: FSMContext):
    """Обработчик команды /upload_cookies, /auth_youtube, /cookies"""
    keyboard = InlineKeyboardMarkup(inline_keyboard=[
        [InlineKeyboardButton(
            text="📋 Вставить cookies текстом",
            callback_data="cookies_paste_text"
        )],
        [InlineKeyboardButton(
            text="📖 Инструкция (yt-dlp wiki)",
            url="https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies"
        )],
        [InlineKeyboardButton(
            text="🔗 Расширение для Chrome",
            url="https://chromewebstore.google.com/detail/get-cookiestxt-locally/cclelndahbckbenkjhflpdbgdldlbecc"
        )],
        [InlineKeyboardButton(
            text="🦊 Расширение для Firefox",
            url="https://addons.mozilla.org/en-US/firefox/addon/cookies-txt/"
        )]
    ])

    await message.answer(
        "🍪 **Обновление YouTube cookies**\n\n"
        "Cookies нужны для скачивания видео и музыки с YouTube.\n\n"
        "**Способ 1 — Текстом (из ytdlnis и др.):**\n"
        "Нажмите кнопку ниже и вставьте cookies текстом\n\n"
        "**Способ 2 — Файлом (из браузера):**\n"
        "1. Установите расширение для браузера\n"
        "2. Откройте YouTube и войдите в аккаунт\n"
        "3. Экспортируйте cookies в файл\n"
        "4. Отправьте файл `youtube_cookies.txt` мне\n\n"
        "🔒 Cookies используются только для скачивания.",
        parse_mode="Markdown",
        reply_markup=keyboard,
        disable_web_page_preview=True
    )


@router.callback_query(F.data == "cookies_paste_text")
async def callback_cookies_paste(callback: CallbackQuery, state: FSMContext):
    """Обработка нажатия кнопки 'Вставить текстом'"""
    await state.set_state(CookiesStates.waiting_for_cookies)
    await callback.message.edit_text(
        "📋 **Вставьте cookies текстом**\n\n"
        "Скопируйте cookies из ytdlnis или другого приложения "
        "и отправьте одним сообщением.\n\n"
        "Формат (Netscape/tab-separated):\n"
        "`\\.youtube.com TRUE / TRUE 1234567890 NAME value`\n\n"
        "Для отмены отправьте /cancel",
        parse_mode="Markdown"
    )
    await callback.answer()


@router.message(Command("cancel"))
async def cmd_cancel(message: Message, state: FSMContext):
    """Отмена текущего состояния"""
    current_state = await state.get_state()
    if current_state is None:
        return
    await state.clear()
    await message.answer("❌ Действие отменено.")


@router.message(CookiesStates.waiting_for_cookies)
async def handle_cookies_text(message: Message, state: FSMContext):
    """Обработка вставленного текста cookies"""
    text = message.text
    if not text:
        await message.answer("❌ Отправьте cookies текстом, не файлом.\nДля отмены: /cancel")
        return

    status_msg = await message.answer("⏳ Обрабатываю cookies...")

    try:
        cookie_content = parse_cookies_text(text)

        if not cookie_content:
            await status_msg.edit_text(
                "❌ **Не удалось распознать cookies**\n\n"
                "Убедитесь что текст содержит YouTube cookies в формате Netscape.\n"
                "Для отмены: /cancel",
                parse_mode="Markdown"
            )
            return

        # Count cookies
        cookie_count = len([l for l in cookie_content.split('\n') if l.strip() and not l.startswith('#')])

        # Save
        with open(COOKIES_PATH, 'w') as f:
            f.write(cookie_content)

        await state.clear()

        logger.info(f"Cookies updated via text by user {message.from_user.id}: {cookie_count} cookies")

        await status_msg.edit_text(
            f"✅ **Cookies обновлены!**\n\n"
            f"📊 Загружено cookies: {cookie_count}\n\n"
            f"🔄 Бот перезапустится через 2 секунды...",
            parse_mode="Markdown"
        )

    except Exception as e:
        logger.error(f"Error saving cookies: {e}")
        try:
            await status_msg.edit_text(
                f"❌ **Ошибка сохранения cookies**\n\n"
                f"`{str(e)}`",
                parse_mode="Markdown"
            )
        except Exception:
            pass
        return

    # Restart bot outside try/except to avoid catching ServerDisconnectedError
    import subprocess
    subprocess.Popen(['bash', '-c', 'sleep 2 && systemctl restart telegram-cover-bot'])


@router.message(F.document)
async def handle_document(message: Message):
    """Обработчик загрузки документов (cookies файла)"""
    document: Document = message.document

    # Проверяем имя файла
    if not document.file_name or 'cookies' not in document.file_name.lower():
        return

    try:
        status_msg = await message.answer("⏳ Загружаю cookies файл...")

        file = await message.bot.get_file(document.file_id)
        await message.bot.download_file(file.file_path, COOKIES_PATH)

        with open(COOKIES_PATH, 'r') as f:
            content = f.read()

        # Basic validation
        if 'youtube.com' not in content:
            await status_msg.edit_text(
                "❌ **Ошибка:** Файл не содержит YouTube cookies.\n\n"
                "Убедитесь, что вы экспортировали cookies с сайта YouTube.",
                parse_mode="Markdown"
            )
            os.remove(COOKIES_PATH)
            return

        cookie_count = len([l for l in content.split('\n') if l.strip() and not l.startswith('#')])

        logger.info(f"Cookies file uploaded by user {message.from_user.id}: {cookie_count} cookies")

        await status_msg.edit_text(
            f"✅ **Cookies успешно загружены!**\n\n"
            f"📊 Статистика:\n"
            f"• Файл: `{document.file_name}`\n"
            f"• Размер: {document.file_size} байт\n"
            f"• Cookies: {cookie_count}\n\n"
            f"🔄 Бот перезапустится через 2 секунды...",
            parse_mode="Markdown"
        )

    except Exception as e:
        logger.error(f"Error uploading cookies: {e}")
        try:
            await message.answer(
                f"❌ **Ошибка при загрузке cookies:**\n\n"
                f"`{str(e)}`",
                parse_mode="Markdown"
            )
        except Exception:
            pass
        return

    import subprocess
    subprocess.Popen(['bash', '-c', 'sleep 2 && systemctl restart telegram-cover-bot'])
